server:
  port: 8228
spring:
  redis:
    timeout: 2000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    local:
      host: localhost
      password:
      port: 6379
    remote:
      host: localhost
      password:
      port: 6379
    jedis:
      pool:
        max-wait:


  datasource:

    mainsource:
      url: jdbc:mysql://localhost:3306/faceMainData?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      maxActive: 10
      maxWait: 3000
      minIdle: 3
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false


    sptsource:
      url: jdbc:mysql://localhost:3306/faceSptData?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      maxActive: 10
      maxWait: 3000
      minIdle: 3
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

  jpa:
    database: mysql
    show-sql: true

project:
  redis:
    prefix: facerecoginition_dlib_20_sub'


